### ISSUE TITLE
Simulate and plot traces of accumulation similarly to typical Wiener model representation

### ISSUE THREAD

**Issue by DominiqueMakowski** [rtdists/rtdists#18]
Hi @singmann, I am trying to finally dig into sequential models for RT, and I first wanted to thank you for your awesome work (in the brms blogpost, this repo or fddm), it's been absolutely critically helpful :)

I am trying to get a better intuition of the parameters of a typical Wiener model, and try to re-create this type of figures:

![image](https://github.com/rtdists/rtdists/assets/8875533/13c3f2b6-7037-440d-be9b-83e660ccbf68)

and to simulate traces for various parameters. 

``` r
library(ggplot2)
#> Warning: package 'ggplot2' was built under R version 4.2.2
library(patchwork)

# Upper distribution plot
upper <- data.frame(x = seq(0, 2, length.out=1000))
upper$y <- rtdists::ddiffusion(upper$x, response = "upper", v = 1, t0 = 0.2, a = 1)

# Simulate traces
traces <- data.frame()
for(i in 1:5) {
  traces <- rbind(traces,
                  data.frame(
    y = cumsum(rnorm(100, 1, 1)),  # drift (mu) = 1
    x = seq(0.2, 2, length.out=100),  # ndt = 0.2
    iter = as.character(i)
  ) 
  )
}

(ggplot(upper, aes(x = x, y = y)) + geom_area()) /
  (ggplot(traces, aes(x = x, y = y, group = iter)) + geom_line() + coord_cartesian(xlim = c(0, 2)))
```

![](https://i.imgur.com/sRbX0Wm.png)

<sup>Created on 2023-05-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

In my attempt, I set the **drift rate** as the mean of the normal distribution of the random walk. But I think something is off with the scale (the x axis over which the trace get generated). Would you know how to simulate traces for a distribution like the one plotted above? (v = 1, t0 = 0.2, a = 1).

Thanks a lot for any pointers and help!

**Comment by singmann** [comment]
You forgot that the **average slope is equal to v**, where the average is given on the second scale. More specifically, in your example  the slope is 1 per step, but it needs to be 1 for 1 second. You need to scale both mean and SD of the normal distribution by your step size (i.e., what is the time in seconds passed at each step). Note for the the SD you need to consider that the stepsize scaling applies to the variance scale.

Another problem is that for the diffusion model the lower bound is 0, so you need to add the starting point as well, which is given by a * 0.5 (for unbiased responding).

The following should work:
``` r
library(ggplot2)
library(patchwork)

max_seconds <- 2
stepsize_seconds <- 0.01

v <- 1
a <- 1

# Upper distribution plot
upper <- data.frame(x = seq(0, max_seconds, length.out=1000))
upper$y <- rtdists::ddiffusion(upper$x, response = "upper", v = v , t0 = 0.2, a = a)

set.seed(9997)
# Simulate traces
traces <- data.frame()
for(i in 1:10) {
  tmp <- data.frame(
    y = cumsum(c(0, rnorm(
      n = max_seconds * 1/stepsize_seconds, 
      mean = v * stepsize_seconds,         ## mean drift for 1 second is v 
      sd = 1 * sqrt(stepsize_seconds)      ## variance grows by sqrt(stepsize)
      ))) + 0.5 * a,                       ## need to add 0.5 * a to start at start point
    x = seq(0, max_seconds, by = stepsize_seconds) + 0.2,  # ndt = 0.2
    iter = as.character(i)
  )
  if (any(tmp$y >= a) & any(tmp$y <= 0)) {
    if (which(tmp$y >= a)[1] < which(tmp$y <= 0)[1]) {
      tmp$y[which(tmp$y >= a)[1]:nrow(tmp)] <- a
    } else {
      tmp$y[which(tmp$y <= 0)[1]:nrow(tmp)] <- 0
    }
  } else if (any(tmp$y >= a)) {
    tmp$y[which(tmp$y >= a)[1]:nrow(tmp)] <- a
  } else if (any(tmp$y <= 0)) {
    tmp$y[which(tmp$y <= 0)[1]:nrow(tmp)] <- 0
  }
  
  traces <- rbind(traces,tmp)
}

(ggplot(upper, aes(x = x, y = y)) + geom_area()) /
  (ggplot(traces, aes(x = x, y = y, group = iter)) + geom_line() + coord_cartesian(xlim = c(0, 2)))
```

![](https://i.imgur.com/BZswAh3.png)

<sup>Created on 2023-05-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Let me know if anything is unclear, this is a great question!

**Comment by DominiqueMakowski** [comment]
Awesome thanks a ton that's super helpful! 

Maybe one last thing, if I wanted to add a bit of `st0` in that (i.e., some variability around ndt), in the docs it says:

`Range of a uniform distribution with mean t0 + st0/2 describing the distribution of actual t0 values across trials.`

I am assuming I would need to add something like `runif()` after adding the `ndt`, but I have doubts regarding the range, is it (0, t0 + st0/2)?

**Comment by singmann** [comment]
The mean is `t0 + st0/2`, so `t0` is the lower limit and `t0 + st0` the upper limit.

**Comment by DominiqueMakowski** [comment]
Cheers :)

**Comment by DominiqueMakowski** [comment]
Just to note, in the docs it says that st0 `Accounts for response times below t0` but actually based on simulations the observed values will never go below t0 so the statement is a bit confusing I think

**Comment by singmann** [comment]
That is correct, the lower bound is always t0.
